//what we do section
$(document).ready(function(){
    $("#design-image").click(function(){
      $("#design-image").slideDown().hide()
      $("#design").show();
    });
    $("#design").click(function(){
      $("#design").slideUp();
      $("#design-image").slideDown();
    });
  });
$(document).ready(function(){
    $("#development-image").click(function(){
      $("#development-image").slideDown().hide()
      $("#development").show();
    });
    $("#development").click(function(){
      $("#development").slideUp();
      $("#development-image").slideDown();
    });
});
$(document).ready(function(){
  $("#product-image").click(function(){
    $("#product-image").slideDown().hide()
    $("#product").show();
  });
  $("#product").click(function(){
    $("#product").slideUp();
    $("#product-image").slideDown();
  });
});
//poertfolio text overlay images
$(document).ready(function(){
  $("#work1").mouseover(function(){
    $("#overlay").show();
  }).mouseout(function(){
    $("#overlay").hide();
  });
});
$(document).ready(function(){
  $("#work2").mouseover(function(){
    $("#overlay2").show();
  }).mouseout(function(){
    $("#overlay2").hide();
  });
});
